### ISSUE TITLE
It should be possible to regenerate $n$ test files without restarting the tests $n$ times

### ISSUE THREAD

**Issue by oxinabox** [Evizero/ReferenceTests.jl#3]
When I change the output of my function to produce a different string,
then I know that all of my reference tests are going to fail.

So I delete my 5 test files.

Now, to recreate them I have to rerun julia 5 times.
because after recreating the test files it throws an error.

 I think instead of throwing an error it should do something the `testset` can catch.
Like maybe an `@test false` or an `@test_broken false` ?

**Comment by Evizero** [comment]
I know exactly what you are saying just by reading the title. I have encountered this before. I agree this should be changed. I actually thought I made the change already

I think this can be fixed by putting lines like this in a `warn` instead of `error` https://github.com/Evizero/ReferenceTests.jl/blob/master/src/test_reference.jl#L108 . maybe with a `@test false`, but I think failed tests also abort the test sequence

**Comment by oxinabox** [comment]
This is really annoying and is still happening.
